### ISSUE TITLE
Population Density API should expose Population Density

### ISSUE THREAD

**Issue by gregory1g** [camaraproject/PopulationDensityData#14]
**Problem description**
API is called population density data, however it exposes population count, not denisty:
"
    populationData:
      dataType: DENSITY_ESTIMATION
      maxPopulation: 150
      minPopulation: 30
      avgPopulation: 60"
Moreover dataType is "DENSITY_ESTIMATION" while the exposed data is not a density - this is misleading.

**Expected behavior**
Api name, data types, attributes names must match like:
    PopulationDensityData:
      dataType: PPL_DENSITY_ESTIMATION
      max: 150
      min: 30
      avg: 60"

**Comment by jgarciahospital** [comment]
Meeting discussion: Analyze offline to make sure that API response is aligned with API name

- Or to change the API name to "count"
- Or to change the response unit from people/cell to people/km2

AP: Also to define the meaning of "max" and "min" in the calculated forecast. Also reconsider average as a forecast response, maybe just "expected"/"forecasted" population value

**Comment by jgarciahospital** [comment]
Decision to change response units to **people/km2**

Definitions to be discussed in #23
