### ISSUE TITLE
Add links to open API spec in ReDoc and Swagger Editor 

### ISSUE THREAD

**Issue by gregory1g** [camaraproject/PopulationDensityData#15]
**Problem description**
To view an API in a Swagger Editor one need to do few manual steps (every time).

**Possible evolution**
Add direct links to view the API specification in ReDoc and Swagger Editor in the main read.me like this is done for other APIs (for example https://github.com/camaraproject/SimSwap)

**Comment by jgarciahospital** [comment]
AFAIK, only released APIs are including such schema. In any case, for simplicity while reviewing the code, I'll open a PR to include the link to the WIP yaml.

**Comment by gregory1g** [comment]
Having these links is handy independent on "released state": in the main branch - to the API version which is currently in main branch (which is mostly always a WIP), in the release branch - to the released version.

**Comment by jgarciahospital** [comment]
Agreed and solved in #19
