### ISSUE TITLE
Discussion of Response parameter definition

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/PopulationDensityData#23]
Continuing with issue #14 
_Also to define the meaning of "max" and "min" in the calculated forecast. Also reconsider average as a forecast response, maybe just "expected"/"forecasted" population value_

Proposal of definition of the output parameters:

Minimum population per km²: refers to the fewest number of predicted individuals per square kilometer attributed to the spatial division in the time period given.
 
Maximum population per km²: refers to the highest number of predicted individuals per square kilometer attributed to the spatial division in the time period given.
 
Average population per km²: refers to the number of the predicted typical individuals per square kilometer attributed to the spatial division in the time period given.

**Comment by gregory1g** [comment]
**Thoughs:**

1. Average is not the same as "number of predicted typical individuals".  Moreover, "number of the predicted typical individuals"   is an unclear term - who are "typical individuals" and how are they differ from other type of individuals?

2. As we have discussed min/max for a predicted value could have different meaning depending on the assumed probability distribution, used algorithm, and even business requirements. This opens 3 possibilities:
a. remove max/min from the response.
b. Keep max/min and define their exact definitions (like [min-max] must cover 90% probability) - this promise to push strong requirements on the algorithms MNO use. It is also not clear which threshold must be enforced by the API (different use cases could prefer different threshold) - does not looks promising
c. allow every MNO to decide (and document) what do provide as min/max. One MNO can declare that this range covers 95% of distribution, another can cover 66%, third can declare that this is just a  +/- 10% from the predicted value.

SORA use case needs max pplDensinty, for the flight: in all three scenarios (a, b, c) an ASP still must calculate max ppl density for the planned flight path and for the flight duration. On the other hand, PplDenisty value for a grid cell does not consider people distribution inside grid cell and we are talking about a prediction for a value which is influenced by many factors out of MNO control or even knowledge (like planned road works). In this context max expected ppl. density which is based on MNO data only is not a big help.

**Suggestions:**
naming:
- use "pplDensity" - for predicted population density in a grid cell
- use "minPplDensity" - for minimal predicted population density in a grid cell
- use "maxPplDensity" - for maximal predicted population density in a grid cell

MinMax:
 - remove minPplDensity and maxPplDensity (see option "a" above) from the first API version.
 - Every MNO can document accuracy of its prediction algorithm.

**Comment by jgarciahospital** [comment]
Agreed to keep definitions proposed by @gregory1g , PR will be created
