### ISSUE TITLE
Discussion on API access mechanism

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/PopulationDensityData#24]
During followup#7, discussion about the usage of 2-3 legged access tokens for this API(s) was raised as AoB.

Offline feedback to be provided.

**Comment by jgarciahospital** [comment]
As in [Follow-up meeting #8](https://wiki.camaraproject.org/display/CAM/2024-05-22+Population+Density+Data+-+Meeting+Minutes), APi is to be considered as 2-legged access token. @bigludo7 is it required any modification in the API spec?

**Comment by bigludo7** [comment]
> As in [Follow-up meeting #8](https://wiki.camaraproject.org/display/CAM/2024-05-22+Population+Density+Data+-+Meeting+Minutes), APi is to be considered as 2-legged access token. @bigludo7 is it required any modification in the API spec?

@jgarciahospital I think we are good as we have:

```
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
```


To be 100% sure adding  @AxelNennker to get his feedback

**Comment by gregory1g** [comment]
I just heard that this QoD PR is the currently expected way to define security schemas: https://github.com/camaraproject/QualityOnDemand/pull/295/files

As far as I understood openID (as in the QoD example) automatically means 3-legged. So, since pplDensity is client-credentials it should not use openID.

Also a purpose and scope must be indicated.

However, my interpretation can be inaccurate.

**Comment by jgarciahospital** [comment]
OIDC is generally including both options, and it's generically included in the APIs where the option is opened, as the rule that applies depending on each region-regulation is that:

_It is important to remark that in cases where personal user data is processed by the API, and users can exercise their rights through mechanisms such as opt-in and/or opt-out, the use of 3-legged access tokens becomes mandatory. This measure ensures that the API remains in strict compliance with user privacy preferences and regulatory obligations, upholding the principles of transparency and user-centric data control._

So, up to know, we consider that the generic reference to OIDC is ok for this API, as also it's only considering Scopes (not PI scopes), but I agree that maybe commonalities or Identity&Consent should also consider this situation where the API is never considered as 3-legged at all. If that is finally agreed we can update based on commonalities.

**Comment by jgarciahospital** [comment]
To be considered in next I&C release as current discussions are already closed. OpenIDConnect is defined as the generic auth, which in this case implies clientCredentials.

**Comment by gregory1g** [comment]
I do agree with @AxelNennker. We have discussed and agreed that this API must be exposed using client credentials - this design decision must be documented in the API.

**Comment by jgarciahospital** [comment]
Since I&CM group is not considering it, I'd prefer to stick in the current official WoW which is still generic OIDC, waiting for the next guidelines in the next meta release.

Proposal is then to maintain current generic OIDC and adapt for following version, when I&CM and commonalities are clearer on this topic.

**Comment by AxelNennker** [comment]
@jgarciahospital 
I see it as a step back if e.g. [qos_profiles.yaml](https://github.com/camaraproject/QualityOnDemand/blob/main/code/API_definitions/qos-profiles.yaml#L131) would remove their oAuth2ClientCredentials security-scheme definition just to be compliant with the API Design Guideline. API Consumers would loose information.

I do not see a problem with adding e.g.

```
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.example.com/oauth/token
          scopes: {}
```

Whether or not client_credentials is allowed for a client is decided/granted at onboarding time. I would like to keep these onboarding concerns out of these technical documents.
I am a strong supporter for OpenId Connect when personal information is involved.
But I think the API Design Guidelines should include guidelines for client_credentials if an API, like qos-profile, needs client_credentials. The information about the grant types should be in the technical documentation for API consumers like the yaml files. I think uniform security schemes are valuable and that API subgroups should not each invent their own security scheme, but I think it makes no sense to force API subgroups to use one security scheme that does not fit their needs.

**Comment by jgarciahospital** [comment]
@AxelNennker while I understand it, I'm not comfortable modifying current version while there is not common agreement apart from the generic OIDC profiling. As soon as there is a mandate coming from TSC, I&CM or commonalities, we'll adapt as in any other required rule, but up to now I still suggest to maintain ourselves aligned with the current rules (of course, not asking other APIs to do the same).

**Comment by AxelNennker** [comment]
I am suggesting to add an oauth2 security scheme to Camara guidelines.
https://github.com/camaraproject/IdentityAndConsentManagement/issues/171
I think it is easy enough. I do not see the problem with adding a guideline on "your" security scheme oAuth2ClientCredentials. I am trying to get a guideline on oauth2 client credentials into Camara guidelines, so that APIs like PopulationDensityData can specify what it needs. Would be nice if you support this effort.

**Comment by AxelNennker** [comment]
After DT-internal discussion we decided not to re-visit the TSC agreement from December.
So, the probably to be release guideline is that API have one security scheme and that is openid.

**Comment by jgarciahospital** [comment]
As discussed in Followup#9, API code is not to be modified, as following guidelines of I&CM of generic security scheme of OIDC, but documentation (as note) will be included to clarify this exact case (2-legged as no personal information).

**Comment by eric-murray** [comment]
@AxelNennker 
> Deferring to discovery does not help because the authorization server might support all kinds of flows and does not provide any info which flow is expected at specific endpoints.

You appear to be making an implicit assumption that an API provider can only provide a single OIDC discovery URL that is common to all APIs. I didn't think that was the case - I see no reason why the `openIdConnectUrl‎` cannot be API specific, given that it is separately specified in each YAML.

So an API provider could specify:
```
openIdConnectUrl: https://api.developerportal.com/camara/population-density-data/.well-known/openid-configuration
```

In this case, the configuration would only list `client_credentials` within `grant_types_supported`, and the potential API consumer would then know what was expected of them. Whilst an API consumer (i.e. developer) would only get final details of authorisation scheme when they are onboarded, they could check this public discovery document in advance (should the API provider publish them separately in this way)  without directly contacting the API provider.

**Comment by AxelNennker** [comment]
> @AxelNennker
> 
> > Deferring to discovery does not help because the authorization server might support all kinds of flows and does not provide any info which flow is expected at specific endpoints.
> 
> You appear to be making an implicit assumption that an API provider can only provide a single OIDC discovery URL that is common to all APIs. I didn't think that was the case - I see no reason why the `openIdConnectUrl‎` cannot be API specific, given that it is separately specified in each YAML.
> 
> So an API provider could specify:
> 
> ```
> openIdConnectUrl: https://api.developerportal.com/camara/population-density-data/.well-known/openid-configuration
> ```
> 
> In this case, the configuration would only list `client_credentials` within `grant_types_supported`, and the potential API consumer would then know what was expected of them. Whilst an API consumer (i.e. developer) would only get final details of authorisation scheme when they are onboarded, they could check this public discovery document in advance (should the API provider publish them separately in this way) without directly contacting the API provider.

I know that. You could even go further and, an API with several endpoints could even have an endpoint-dependent meta-data url
```
openIdConnectUrl: https://api.developerportal.com/camara/population-density-data/retrieve/.well-known/openid-configuration
```

The text in https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md#use-of-openidconnect-for-securityschemes is this:

> The value for openIdConnectUrl in the CAMARA spec is an example, that must be substituted by the specific discovery endpoint for OIDC protocol of the API provider, when the API is exposed in one of its environments.

Which makes the assumption that openIdConnectUrl is the discovery endpoint of the API provider.

In Keycloak the Camara admin would then need to create a separate realm for each API, I think.
Or we host the openid-configuration somewhere else.

The ICM guidelines mandate that there is exactly **one** security scheme.
Specifying different security-schemes for endpoints is not possible. Maybe that use-case does not exist. Who knows?!

I think, that specifying different discovery URL whether OIDC or CIBA or client credentials be used is a hack.

If you think this is the way to go then we should have guidelines regarding this in ICM https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md#use-of-openidconnect-for-securityschemes

**Comment by eric-murray** [comment]
> I think, that specifying different discovery URL whether OIDC or CIBA or client credentials be used is a hack.

That wasn't my proposal at all. The proposal is that the discovery endpoint be **API specific** (not authentication scheme specific). If an API implementation supports or requires multiple authentication schemes, then the discovery endpoint for that API will list all of these.

**Comment by jgarciahospital** [comment]
@AxelNennker @eric-murray I think this is a pretty interesting discussion that should be handled in a broader forum than PopulationDensityData API. Can you please continue the conversation in an ad-hoc issue in I&CM?

**Comment by AxelNennker** [comment]
> @AxelNennker @eric-murray I think this is a pretty interesting discussion that should be handled in a broader forum than PopulationDensityData API. Can you please continue the conversation in an ad-hoc issue in I&CM?

I created https://github.com/camaraproject/IdentityAndConsentManagement/issues/176 in ICM after the TSC meeting.
We can discuss the various aspects there. Both technical aspects like disovery-url in THE security-scheme, and guidelines for API designers and API consumers and Telcos who implement an authorization server.

**Comment by jgarciahospital** [comment]
Thanks @AxelNennker 

As agreed during [Population Density Meeting](https://wiki.camaraproject.org/display/CAM/2024-06-05+Population+Density+Data+-+Meeting+Minutes) for this APi version:

- Not modify security schema in the API code, as no different guidance in I&CM group is determined apart from OIDC
- Include clarification text in API documentation, establishing that the usage of this API is determined by CAMARA rules, in this case 2-leggged as no personal data is treated. 


#30 includes such changes
