### ISSUE TITLE
Validate API code and align with commonalities (meta-release item 1-2-3)

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/PopulationDensityData#38]
- Confirm API definition
-  Design guidelines from Commonalities applied (TBC)
- Guidelines from ICM applied  (TBC)

**Comment by bigludo7** [comment]
Hello @jgarciahospital 
For me we have an issue for the webhook as it is not aligned with commonalities 0.4.0

This is not a big change but as we're close to the deadline this is tricky.

See [here](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#instance-based-implicit-subscription) the guidance

**Comment by rartych** [comment]
I think here is asynchronous response, so I am not sure if guidelines related to event notification should be applied.

**Comment by bigludo7** [comment]
> I think here is asynchronous response, so I am not sure if guidelines related to event notification should be applied.

I think as this is the same concept (use an url) we should use same attribute 'name'for developer's sake. But I got your point @rartych that this is not subscription. If you consider this is not an issue to commonalities v0.4 this is fine for me. 
(I can raise an issue for name alignement for next release).

**Comment by jgarciahospital** [comment]
As proposed in the #44:

Making one additional review we find that QoD API suffered similar issue and finally they made the alignement (this [Issue](https://github.com/camaraproject/QualityOnDemand/issues/332) & [PR](https://github.com/camaraproject/QualityOnDemand/pull/335) summarizes). So, just for aligning with https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#instance-based-implicit-subscription, let me propose to roll back to initial plan and:

- Update gherkin to be aligned with async auth
- Update API yaml (I'll create a separate PR moving back to wip version)
- Later we can sync this with the release PR
