### ISSUE TITLE
Discussion on API spec -  Default and limit values for the API characteristics

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/PopulationDensityData#7]
During meeting held on 7th february, open questions were raised:
* **Minimum and maximum date** minimum and maximum date allowed as requested time range. Currently, 15 minutes is set as the minimum (soonest time target the request can consider), and 1 year for maximum (longer date with information to extrapolate). TBD

* **Time interval** in the request: Maximum (and minimum) lenght of the time range requested in the API. TBD

* **Time granularity** in the response: Lenght of the information pieces in which the time interval is subdivided in the response. Default value is proposed in 1hour, so the response will include density information of each 1hour range that can be included in the requested interval. E.g. If request interval is 15minutes to 1 hour, 1 only result will be provided, if 3 hours and 45 minutes are requested, 4 results will be provided (from 0-1, 1-2, 2-3, 3-3:45). TBD
* **Cell size/granularity** in the response: Currently both cell definition systems allow to implement different size of cells.  TBD

Participants are invited to provide their view about this issue →

**Comment by sachinvodafone** [comment]
On "**Minimum and maximum date** ":  If certain providers have the ability to offer relevant and accurate information within a shorter time frame (< 15mins) as well, I believe , it should reasonable to consider adjusting the API specifications to accommodate their capabilities and shouldn't restrict them for 15minute minimum time frame .


on "**Cell size/granularity** " :  When we talk about splitting the polygon into equal-sized cells, are we suggesting different approaches to developer to achieve the same like **Bounding Box** Approach that will ensures that the entire polygon is included and gives a simple way to create cells of the same size. However, in this approach, some cells might go beyond the polygon's actual boundaries, which could introduce inaccuracies.

And other option to  create **Equal-Sized** Cells Within the Polygon itself that will ensures that all cells stay inside the specified polygon, potentially providing more accurate estimates of population density. However,  this approach can be more computationally complex for implementation, and the cells may not be perfectly equal in size due to the irregular shape of the polygon.

**Comment by jgarciahospital** [comment]
Hi @sachinvodafone, 

1. About time frame limits, agree on minimum date. I think we can consider a time frame from t=0, but according to the scope of the API all the data will be calculated as a prediction. Are you proposing to provide real & current data?

### Proposed WF: Close time frame limits in t=0 (min) and t=1year (max) with data prediction algorithm in all the timeframe

2. About cellsize, If focusing on geohash cells, having equal-sized cells and agreeing on the size of those among providers can be easilly managed. 

### Proposed WF: Document in the API yaml that response will include equal-sized cells, focusing on the geohash cells format.

3. Lenght of the time frame: As stated, the minimum will be 1 set of data in case the timeframe lenght is shorter than the granularity, and we propose to stablish X days as maximum, at least for this version, since we consider that feasible and suitable for the reference use case, and also considering the size of the data required for the response. The proposed stablished on previous call, with 7 days (1 week) is ok to be consiedered as default.

### Proposed WF: 1 week (7 days) is proposed as maximum time frame length.

4. Time granularity: Up to now, 1 hour is the default value to consider.

### Proposed WF: maintain 1 hour as the time granularity for the response.

Please share your feedback about this.

**Comment by jgarciahospital** [comment]
### Proposed WF (discussed in the meeting and based on offline discussions):

- Close time frame limits in t=0 (min) and reduce max to t=(6)months (max) with data prediction algorithm in all the timeframe. That covers current use case.
- Document in the API yaml that response will include equal-sized cells, focusing on the geohash cells format.
- 1 week (7 days) is proposed as maximum time frame length.
- Maintain 1 hour as the time granularity for the response.
- Open discussion on maximum requested area size, need to consider a feasible maximum response size jointly with the maximum length of the timeframe.

**To open discussion focusing on open point (maximum requested area size). Feedback required previous to next meeting.** Companies are invited to provide their preference before next meeting (06 March)

**Comment by gregory1g** [comment]
> Close time frame limits in t=0 (min) and reduce max to t=(6)months (max) with data prediction algorithm in all the timeframe.

Why exclude historical data from the API? Probably not needed for the flight control use case, but could be useful for other use cases. Or the whole API servers exactly one use cases?

**Comment by jgarciahospital** [comment]
> > Close time frame limits in t=0 (min) and reduce max to t=(6)months (max) with data prediction algorithm in all the timeframe.
> 
> Why exclude historical data from the API? Probably not needed for the flight control use case, but could be useful for other use cases. Or the whole API servers exactly one use cases?

Hi Gregory, it was decided to focus on this reference use case first where only non-past information is required. We can include such functionality of historical in a following version.

**Comment by jgarciahospital** [comment]
Update from last meeting [06/03 Minutes](https://wiki.camaraproject.org/display/CAM/2024-03-06+Population+Density+Data+-+Meeting+Minutes)

Agreed WF

- Close time frame limits in t=0 (min) and reduce max to t=(3)months (max) with data prediction algorithm in all the timeframe. That covers current use case.
- Document in the API yaml that response will include equal-sized cells, focusing on the geohash cells format.
- 1 week (7 days) is proposed as maximum time frame length.
- Maintain 1 hour as the time granularity for the response.
- Default value on level 7 (150m x 150m) (TBC). **Open Discussion, please provide feedback.**
- Maximum requested area size, need to consider a feasible maximum response size jointly with the maximum length of the timeframe. Dependency with #10 **Open Discussion, please provide feedback.**

**Comment by jgarciahospital** [comment]
Update from last meeting [20/03 Minutes](https://wiki.camaraproject.org/display/CAM/2024-03-20+Population+Density+Data+-+Meeting+Minutes)

**Agreed WF**

→ Open discussion on maintaining the default geohash level in 7, but include an optional parameter in the request for the consumer to select a different value. "Not supported" error to be analyzed on those cases
→ Max area still under discussion

**Comment by sachinvodafone** [comment]
Setting the default geohash to 7 seems suitable. However, the provider should specify to the client which geohash levels it supports, as this may vary among providers, to prevent unnecessary "Not supported" errors.

**Comment by jgarciahospital** [comment]
Support a input parameter for the developer to select level (optional, default ==7), and create a "level not supported" error. To consider in future release the analysis of other global grids.

Solved in #21 

Max area size is leave open (technically) to a reasonable use case management, each operator launch an error in case the size is not supported. To include error in code

**Comment by jgarciahospital** [comment]
Closed as fixed in #21
